### ISSUE TITLE
Change the color of the "Read more" button so that it is easy to read in dark mode. 

### ISSUE THREAD

**Issue by anubhav1206** [anubhav1206/Movie-Saver#6]
![image](https://github.com/anubhav1206/Movie-Saver/assets/53504460/fdf819b6-7fe1-4631-bc3e-635ff75fedef)

The "Read more" text in black color does not look good when dark mode is toggled.

**Comment by rawasaditya** [comment]
Will take care of this assign it to me ,thanks

**Comment by rawasaditya** [comment]
[PR](https://github.com/anubhav1206/Movie-Saver/pull/8)
A simple css fix for this

https://github.com/anubhav1206/Movie-Saver/assets/114228121/920df187-0e97-4f92-935f-9d6db62fa8a2

**Comment by anubhav1206** [comment]
Thanks @rawasaditya , merging your PR.
